### ISSUE TITLE
UCDAACEncoder 错误

### ISSUE THREAD

**Issue by JYungSiu** [umdk/UCDLive_iOS#2]
在把官方的demo集成到我们的项目中时，在启动推流的时候会发生createAudioConvert错误。
我们的项目里面使用的环信用的是不带语音通话功能的版本。
具体的报错堆栈如下，望解惑：
Thread 30Queue : UCD Encoder Queue (serial)
#0	0x1a08f170 in __cxa_begin_catch ()
#1	0x2c7824b8 in GetPropertyInfo(void*, unsigned long, unsigned long*, unsigned char*) ()
#2	0x1d9739d0 in CodecConverter::CheckInitialize(void const*, unsigned long) ()
#3	0x1d9739d0 in CodecConverter::CheckInitialize(void const*, unsigned long) ()
#4	0x1d9736d0 in CodecConverter::CodecConverter(OpaqueAudioComponent*&, OpaqueAudioComponentInstance*, StreamDescPair const&, StreamDescPair const&, bool, AudioConverterPrimeInfo const&) ()
#5	0x1d97410e in CodecConverter::CodecConverter(OpaqueAudioComponent*&, OpaqueAudioComponentInstance*, StreamDescPair const&, StreamDescPair const&, bool, AudioConverterPrimeInfo const&) ()
#6	0x1da324b2 in CodecEncoderFactory::BuildCodecConverterChain(StreamDescPair const&, ChainBuildSettings const&, AudioConverterChain*, PCMConverterFactory*) ()
#7	0x1d7dd7ea in ConverterRegistry::CreateConverter(StreamDescPair const&, AudioConverterChain**, unsigned long, AudioClassDescription const*) ()
#8	0x1da698ce in _AudioConverterNewInternal ()
#9	0x1da699c2 in AudioConverterNewSpecific ()
#10	0x00ab81a8 in -[UCDAACEncoder createAudioConvert] at /Users/yisanmao/Documents/tuxiong/workingSpace/UCDStreamingKit/UCDStreamingKit/AVEncoder/UCDAACEncoder.m:188
#11	0x00ab87c2 in __43-[UCDAACEncoder encodeAudioData:timeStamp:]_block_invoke at /Users/yisanmao/Documents/tuxiong/workingSpace/UCDStreamingKit/UCDStreamingKit/AVEncoder/UCDAACEncoder.m:388
#12	0x01d3ed66 in _dispatch_call_block_and_release ()
#13	0x01d4aed8 in _dispatch_queue_serial_drain ()
#14	0x01d42214 in _dispatch_queue_invoke ()
#15	0x01d4cde0 in _dispatch_root_queue_drain ()
#16	0x01d4cbe8 in _dispatch_worker_thread3 ()
#17	0x1a696936 in _pthread_wqthread ()
#18	0x1a69648c in start_wqthread ()
Enqueued from UCDAudioGraph_audioOutPutQueue (Thread 36)Queue : UCDAudioGraph_audioOutPutQueue (serial)
#0	0x01d492a2 in _dispatch_queue_push ()
#1	0x00ab8788 in -[UCDAACEncoder encodeAudioData:timeStamp:] at /Users/yisanmao/Documents/tuxiong/workingSpace/UCDStreamingKit/UCDStreamingKit/AVEncoder/UCDAACEncoder.m:385
#2	0x00ab052e in -[UCDStreamingSession pushAudioSampleBufferList:completion:] at /Users/yisanmao/Documents/tuxiong/workingSpace/UCDStreamingKit/UCDStreamingKit/UCDStreamingSession.m:245
#3	0x00aa5cca in -[CameraServer outputCapture:audioData:] at /Users/grubby.liu/work/auto_umedia_sdk_build/ijkplayer/ios/ulive-ios-sdk/UCloudMediaRecorder/CameraServer.m:1327
#4	0x00a9f820 in -[UCDAudioCapture audioGraph:didOutputBuffer:info:] at /Users/grubby.liu/work/auto_umedia_sdk_build/ijkplayer/ios/ulive-ios-sdk/UCloudMediaRecorder/UCDAudioCapture.m:544
#5	0x00aaaf08 in __54-[AudioMixergraph needRenderFramesNum:timeStamp:flag:]_block_invoke at /Users/grubby.liu/work/auto_umedia_sdk_build/ijkplayer/ios/ulive-ios-sdk/UCloudMediaRecorder/AudioMixergraph.m:325
#6	0x01d3ed66 in _dispatch_call_block_and_release ()
#7	0x01d4aed8 in _dispatch_queue_serial_drain ()
#8	0x01d42214 in _dispatch_queue_invoke ()
#9	0x01d4cde0 in _dispatch_root_queue_drain ()
#10	0x01d4cbe8 in _dispatch_worker_thread3 ()
#11	0x1a696936 in _pthread_wqthread ()
#12	0x1a69648c in start_wqthread ()
Enqueued from com.apple.root.default-qos.overcommit (Thread 39)Queue : com.apple.root.default-qos.overcommit (serial)
#0	0x01d492a2 in _dispatch_queue_push ()
#1	0x00aaadfe in -[AudioMixergraph needRenderFramesNum:timeStamp:flag:] at /Users/grubby.liu/work/auto_umedia_sdk_build/ijkplayer/ios/ulive-ios-sdk/UCloudMediaRecorder/AudioMixergraph.m:302
#2	0x00a9de4c in handleInputBuffer at /Users/grubby.liu/work/auto_umedia_sdk_build/ijkplayer/ios/ulive-ios-sdk/UCloudMediaRecorder/UCDAudioCapture.m:438
#3	0x1d8bb370 in AUIOHelper::NotifyInputAvailable(AudioTimeStamp const&, unsigned long, AudioBufferList const&) ()
#4	0x1d83ee98 in AURemoteIO::PerformIO(unsigned long, unsigned int, unsigned int, AudioTimeStamp const&, AudioTimeStamp const&, AudioBufferList const*, AudioBufferList*, int&) ()
#5	0x1d840550 in AURIOCallbackReceiver_PerformIO ()
#6	0x1d99cef0 in _XPerformIO ()
#7	0x1db3ab8e in mshMIGPerform ()
#8	0x1db3ad34 in MSHMIGDispatchMessage ()
#9	0x1d83f4c0 in AURemoteIO::IOThread::Run() ()
#10	0x1d843f62 in AURemoteIO::IOThread::Entry(void*) ()
#11	0x1db3feaa in CAPThread::Entry(CAPThread*) ()
#12	0x1a698a16 in _pthread_body ()
#13	0x1a69893c in _pthread_start ()
#14	0x1a696498 in thread_start ()

**Comment by langyapojun** [comment]
你是不是打开了全局断点，是的话继续点击执行即可，或者关闭全局断点

**Comment by JYungSiu** [comment]
好的，关闭全局断点后解决问题。在ReadMe里面备注一下吧，防止有人继续掉坑里。

**Comment by langyapojun** [comment]
好的，感谢反馈
