### ISSUE TITLE
你们ucloud_ufile_sdk demo这段Swift代码用Objective-C要怎么写？

### ISSUE THREAD

**Issue by YEZHENLONG** [umdk/UCDLive_iOS#4]
![5097b747-ab22-496a-bc32-f46a452056bd](https://cloud.githubusercontent.com/assets/14218710/25118643/bbb4f1f6-2449-11e7-9a37-2ab942148d49.png)

**Comment by b9AobJ** [comment]
https://github.com/ufilesdk-dev/ufile-iossdk
